// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cistern.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DumpBinlogReq struct {
	// beginCommitTS speicifies the position from which begin to dump binlogs.
	// note that actually the result of dump starts from the one next to beginCommitTS
	// it should be zero in case of the first request.
	BeginCommitTS        int64    `protobuf:"varint,1,opt,name=beginCommitTS,proto3" json:"beginCommitTS,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpBinlogReq) Reset()         { *m = DumpBinlogReq{} }
func (m *DumpBinlogReq) String() string { return proto.CompactTextString(m) }
func (*DumpBinlogReq) ProtoMessage()    {}
func (*DumpBinlogReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_da1013ee3d8abade, []int{0}
}

func (m *DumpBinlogReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpBinlogReq.Unmarshal(m, b)
}
func (m *DumpBinlogReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpBinlogReq.Marshal(b, m, deterministic)
}
func (m *DumpBinlogReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpBinlogReq.Merge(m, src)
}
func (m *DumpBinlogReq) XXX_Size() int {
	return xxx_messageInfo_DumpBinlogReq.Size(m)
}
func (m *DumpBinlogReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpBinlogReq.DiscardUnknown(m)
}

var xxx_messageInfo_DumpBinlogReq proto.InternalMessageInfo

func (m *DumpBinlogReq) GetBeginCommitTS() int64 {
	if m != nil {
		return m.BeginCommitTS
	}
	return 0
}

type DumpBinlogResp struct {
	// CommitTS specifies the commitTS of binlog
	CommitTS int64 `protobuf:"varint,1,opt,name=commitTS,proto3" json:"commitTS,omitempty"`
	// payloads is bytecodes encoded from binlog item
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// ddljob is json bytes marshaled from corresponding ddljob struct if payload is a DDL type of binlog
	Ddljob               []byte   `protobuf:"bytes,3,opt,name=ddljob,proto3" json:"ddljob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpBinlogResp) Reset()         { *m = DumpBinlogResp{} }
func (m *DumpBinlogResp) String() string { return proto.CompactTextString(m) }
func (*DumpBinlogResp) ProtoMessage()    {}
func (*DumpBinlogResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_da1013ee3d8abade, []int{1}
}

func (m *DumpBinlogResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpBinlogResp.Unmarshal(m, b)
}
func (m *DumpBinlogResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpBinlogResp.Marshal(b, m, deterministic)
}
func (m *DumpBinlogResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpBinlogResp.Merge(m, src)
}
func (m *DumpBinlogResp) XXX_Size() int {
	return xxx_messageInfo_DumpBinlogResp.Size(m)
}
func (m *DumpBinlogResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpBinlogResp.DiscardUnknown(m)
}

var xxx_messageInfo_DumpBinlogResp proto.InternalMessageInfo

func (m *DumpBinlogResp) GetCommitTS() int64 {
	if m != nil {
		return m.CommitTS
	}
	return 0
}

func (m *DumpBinlogResp) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *DumpBinlogResp) GetDdljob() []byte {
	if m != nil {
		return m.Ddljob
	}
	return nil
}

type DumpDDLJobsReq struct {
	// beginCommitTS is the start point of drainer processing binlog, DumpDDLJobs() returns
	// all history DDL jobs before this position, then drainer will apply these DDL jobs
	// in order of job ID to restore the whole schema info at that moment.
	BeginCommitTS        int64    `protobuf:"varint,1,opt,name=beginCommitTS,proto3" json:"beginCommitTS,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpDDLJobsReq) Reset()         { *m = DumpDDLJobsReq{} }
func (m *DumpDDLJobsReq) String() string { return proto.CompactTextString(m) }
func (*DumpDDLJobsReq) ProtoMessage()    {}
func (*DumpDDLJobsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_da1013ee3d8abade, []int{2}
}

func (m *DumpDDLJobsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpDDLJobsReq.Unmarshal(m, b)
}
func (m *DumpDDLJobsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpDDLJobsReq.Marshal(b, m, deterministic)
}
func (m *DumpDDLJobsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpDDLJobsReq.Merge(m, src)
}
func (m *DumpDDLJobsReq) XXX_Size() int {
	return xxx_messageInfo_DumpDDLJobsReq.Size(m)
}
func (m *DumpDDLJobsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpDDLJobsReq.DiscardUnknown(m)
}

var xxx_messageInfo_DumpDDLJobsReq proto.InternalMessageInfo

func (m *DumpDDLJobsReq) GetBeginCommitTS() int64 {
	if m != nil {
		return m.BeginCommitTS
	}
	return 0
}

type DumpDDLJobsResp struct {
	// ddljobs is an array of JSON encoded history DDL jobs
	Ddljobs              [][]byte `protobuf:"bytes,1,rep,name=ddljobs,proto3" json:"ddljobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpDDLJobsResp) Reset()         { *m = DumpDDLJobsResp{} }
func (m *DumpDDLJobsResp) String() string { return proto.CompactTextString(m) }
func (*DumpDDLJobsResp) ProtoMessage()    {}
func (*DumpDDLJobsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_da1013ee3d8abade, []int{3}
}

func (m *DumpDDLJobsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpDDLJobsResp.Unmarshal(m, b)
}
func (m *DumpDDLJobsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpDDLJobsResp.Marshal(b, m, deterministic)
}
func (m *DumpDDLJobsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpDDLJobsResp.Merge(m, src)
}
func (m *DumpDDLJobsResp) XXX_Size() int {
	return xxx_messageInfo_DumpDDLJobsResp.Size(m)
}
func (m *DumpDDLJobsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpDDLJobsResp.DiscardUnknown(m)
}

var xxx_messageInfo_DumpDDLJobsResp proto.InternalMessageInfo

func (m *DumpDDLJobsResp) GetDdljobs() [][]byte {
	if m != nil {
		return m.Ddljobs
	}
	return nil
}

type NotifyReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyReq) Reset()         { *m = NotifyReq{} }
func (m *NotifyReq) String() string { return proto.CompactTextString(m) }
func (*NotifyReq) ProtoMessage()    {}
func (*NotifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_da1013ee3d8abade, []int{4}
}

func (m *NotifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyReq.Unmarshal(m, b)
}
func (m *NotifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyReq.Marshal(b, m, deterministic)
}
func (m *NotifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyReq.Merge(m, src)
}
func (m *NotifyReq) XXX_Size() int {
	return xxx_messageInfo_NotifyReq.Size(m)
}
func (m *NotifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyReq proto.InternalMessageInfo

type NotifyResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyResp) Reset()         { *m = NotifyResp{} }
func (m *NotifyResp) String() string { return proto.CompactTextString(m) }
func (*NotifyResp) ProtoMessage()    {}
func (*NotifyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_da1013ee3d8abade, []int{5}
}

func (m *NotifyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyResp.Unmarshal(m, b)
}
func (m *NotifyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyResp.Marshal(b, m, deterministic)
}
func (m *NotifyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyResp.Merge(m, src)
}
func (m *NotifyResp) XXX_Size() int {
	return xxx_messageInfo_NotifyResp.Size(m)
}
func (m *NotifyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyResp.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DumpBinlogReq)(nil), "pb.DumpBinlogReq")
	proto.RegisterType((*DumpBinlogResp)(nil), "pb.DumpBinlogResp")
	proto.RegisterType((*DumpDDLJobsReq)(nil), "pb.DumpDDLJobsReq")
	proto.RegisterType((*DumpDDLJobsResp)(nil), "pb.DumpDDLJobsResp")
	proto.RegisterType((*NotifyReq)(nil), "pb.NotifyReq")
	proto.RegisterType((*NotifyResp)(nil), "pb.NotifyResp")
}

func init() { proto.RegisterFile("cistern.proto", fileDescriptor_da1013ee3d8abade) }

var fileDescriptor_da1013ee3d8abade = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0x2c, 0x2e,
	0x49, 0x2d, 0xca, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x92, 0x12, 0x49,
	0xcf, 0x4f, 0xcf, 0x07, 0x73, 0xf5, 0x41, 0x2c, 0x88, 0x8c, 0x92, 0x29, 0x17, 0xaf, 0x4b, 0x69,
	0x6e, 0x81, 0x53, 0x66, 0x5e, 0x4e, 0x7e, 0x7a, 0x50, 0x6a, 0xa1, 0x90, 0x0a, 0x17, 0x6f, 0x52,
	0x6a, 0x7a, 0x66, 0x9e, 0x73, 0x7e, 0x6e, 0x6e, 0x66, 0x49, 0x48, 0xb0, 0x04, 0xa3, 0x02, 0xa3,
	0x06, 0x73, 0x10, 0xaa, 0xa0, 0x52, 0x1c, 0x17, 0x1f, 0xb2, 0xb6, 0xe2, 0x02, 0x21, 0x29, 0x2e,
	0x8e, 0x64, 0x54, 0x2d, 0x70, 0xbe, 0x90, 0x04, 0x17, 0x7b, 0x41, 0x62, 0x65, 0x4e, 0x7e, 0x62,
	0x8a, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x8c, 0x2b, 0x24, 0xc6, 0xc5, 0x96, 0x92, 0x92,
	0x93, 0x95, 0x9f, 0x24, 0xc1, 0x0c, 0x96, 0x80, 0xf2, 0x94, 0xcc, 0x20, 0xe6, 0xbb, 0xb8, 0xf8,
	0x78, 0xe5, 0x27, 0x15, 0x13, 0xef, 0x2e, 0x6d, 0x2e, 0x7e, 0x14, 0x7d, 0xc5, 0x05, 0x20, 0xcb,
	0x21, 0x86, 0x16, 0x4b, 0x30, 0x2a, 0x30, 0x83, 0x2c, 0x87, 0x72, 0x95, 0xb8, 0xb9, 0x38, 0xfd,
	0xf2, 0x4b, 0x32, 0xd3, 0x2a, 0x83, 0x52, 0x0b, 0x95, 0x78, 0xb8, 0xb8, 0x60, 0x9c, 0xe2, 0x02,
	0xa3, 0xe5, 0x8c, 0x5c, 0xec, 0xce, 0x90, 0x20, 0x14, 0x32, 0xe7, 0xe2, 0x42, 0xf8, 0x55, 0x48,
	0x50, 0xaf, 0x20, 0x49, 0x0f, 0x25, 0xc8, 0xa4, 0x84, 0xd0, 0x85, 0x8a, 0x0b, 0x94, 0x18, 0x0c,
	0x18, 0x85, 0x2c, 0xb8, 0xb8, 0x91, 0x1c, 0x23, 0x04, 0x57, 0x86, 0xf0, 0x95, 0x94, 0x30, 0x86,
	0x18, 0x48, 0xaf, 0x90, 0x26, 0x17, 0x1b, 0xc4, 0x31, 0x42, 0xbc, 0x20, 0x05, 0x70, 0x57, 0x4a,
	0xf1, 0x21, 0x73, 0x41, 0x4a, 0x9d, 0x78, 0x4e, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1,
	0xc1, 0x23, 0x39, 0xc6, 0x24, 0x36, 0x70, 0xac, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x2c,
	0x64, 0x5d, 0xd0, 0x00, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CisternClient is the client API for Cistern service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CisternClient interface {
	// DumpBinlog dumps continuous binlog items in a stream from a given position
	DumpBinlog(ctx context.Context, in *DumpBinlogReq, opts ...grpc.CallOption) (Cistern_DumpBinlogClient, error)
	// DumpDDLJobs dumps all history DDL jobs before a specified commitTS
	DumpDDLJobs(ctx context.Context, in *DumpDDLJobsReq, opts ...grpc.CallOption) (*DumpDDLJobsResp, error)
	// Notify notifies all living cisterns that a new pump is coming
	// the living cisterns can be queried from pd
	Notify(ctx context.Context, in *NotifyReq, opts ...grpc.CallOption) (*NotifyResp, error)
}

type cisternClient struct {
	cc *grpc.ClientConn
}

func NewCisternClient(cc *grpc.ClientConn) CisternClient {
	return &cisternClient{cc}
}

func (c *cisternClient) DumpBinlog(ctx context.Context, in *DumpBinlogReq, opts ...grpc.CallOption) (Cistern_DumpBinlogClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Cistern_serviceDesc.Streams[0], "/pb.Cistern/DumpBinlog", opts...)
	if err != nil {
		return nil, err
	}
	x := &cisternDumpBinlogClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cistern_DumpBinlogClient interface {
	Recv() (*DumpBinlogResp, error)
	grpc.ClientStream
}

type cisternDumpBinlogClient struct {
	grpc.ClientStream
}

func (x *cisternDumpBinlogClient) Recv() (*DumpBinlogResp, error) {
	m := new(DumpBinlogResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cisternClient) DumpDDLJobs(ctx context.Context, in *DumpDDLJobsReq, opts ...grpc.CallOption) (*DumpDDLJobsResp, error) {
	out := new(DumpDDLJobsResp)
	err := c.cc.Invoke(ctx, "/pb.Cistern/DumpDDLJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cisternClient) Notify(ctx context.Context, in *NotifyReq, opts ...grpc.CallOption) (*NotifyResp, error) {
	out := new(NotifyResp)
	err := c.cc.Invoke(ctx, "/pb.Cistern/Notify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CisternServer is the server API for Cistern service.
type CisternServer interface {
	// DumpBinlog dumps continuous binlog items in a stream from a given position
	DumpBinlog(*DumpBinlogReq, Cistern_DumpBinlogServer) error
	// DumpDDLJobs dumps all history DDL jobs before a specified commitTS
	DumpDDLJobs(context.Context, *DumpDDLJobsReq) (*DumpDDLJobsResp, error)
	// Notify notifies all living cisterns that a new pump is coming
	// the living cisterns can be queried from pd
	Notify(context.Context, *NotifyReq) (*NotifyResp, error)
}

// UnimplementedCisternServer can be embedded to have forward compatible implementations.
type UnimplementedCisternServer struct {
}

func (*UnimplementedCisternServer) DumpBinlog(req *DumpBinlogReq, srv Cistern_DumpBinlogServer) error {
	return status.Errorf(codes.Unimplemented, "method DumpBinlog not implemented")
}
func (*UnimplementedCisternServer) DumpDDLJobs(ctx context.Context, req *DumpDDLJobsReq) (*DumpDDLJobsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpDDLJobs not implemented")
}
func (*UnimplementedCisternServer) Notify(ctx context.Context, req *NotifyReq) (*NotifyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}

func RegisterCisternServer(s *grpc.Server, srv CisternServer) {
	s.RegisterService(&_Cistern_serviceDesc, srv)
}

func _Cistern_DumpBinlog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DumpBinlogReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CisternServer).DumpBinlog(m, &cisternDumpBinlogServer{stream})
}

type Cistern_DumpBinlogServer interface {
	Send(*DumpBinlogResp) error
	grpc.ServerStream
}

type cisternDumpBinlogServer struct {
	grpc.ServerStream
}

func (x *cisternDumpBinlogServer) Send(m *DumpBinlogResp) error {
	return x.ServerStream.SendMsg(m)
}

func _Cistern_DumpDDLJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpDDLJobsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CisternServer).DumpDDLJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Cistern/DumpDDLJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CisternServer).DumpDDLJobs(ctx, req.(*DumpDDLJobsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cistern_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CisternServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Cistern/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CisternServer).Notify(ctx, req.(*NotifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cistern_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Cistern",
	HandlerType: (*CisternServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DumpDDLJobs",
			Handler:    _Cistern_DumpDDLJobs_Handler,
		},
		{
			MethodName: "Notify",
			Handler:    _Cistern_Notify_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DumpBinlog",
			Handler:       _Cistern_DumpBinlog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cistern.proto",
}
