// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

/*
Package firstapp_proto is a generated protocol buffer package.

It is generated from these files:
	account.proto
	api.proto
	common.proto

It has these top-level messages:
	Account
	CreateAccountRequest
	CreateAccountResponse
	AccountQueryRequest
	AccountResponse
	Status
	Ping
	Pong
*/
package firstapp_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountStatus int32

const (
	AccountStatus_DISABLED AccountStatus = 0
	AccountStatus_ENABLED  AccountStatus = 1
)

var AccountStatus_name = map[int32]string{
	0: "DISABLED",
	1: "ENABLED",
}
var AccountStatus_value = map[string]int32{
	"DISABLED": 0,
	"ENABLED":  1,
}

func (x AccountStatus) String() string {
	return proto.EnumName(AccountStatus_name, int32(x))
}
func (AccountStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AccountType int32

const (
	AccountType_USER     AccountType = 0
	AccountType_BANK     AccountType = 1
	AccountType_MERCHANT AccountType = 2
)

var AccountType_name = map[int32]string{
	0: "USER",
	1: "BANK",
	2: "MERCHANT",
}
var AccountType_value = map[string]int32{
	"USER":     0,
	"BANK":     1,
	"MERCHANT": 2,
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}
func (AccountType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Account struct {
	Acno        string        `protobuf:"bytes,1,opt,name=acno" json:"acno,omitempty"`
	Uid         int64         `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Cino        string        `protobuf:"bytes,3,opt,name=cino" json:"cino,omitempty"`
	Memo        string        `protobuf:"bytes,4,opt,name=memo" json:"memo,omitempty"`
	CreatedTime string        `protobuf:"bytes,5,opt,name=created_time,json=createdTime" json:"created_time,omitempty"`
	Status      AccountStatus `protobuf:"varint,6,opt,name=status,enum=firstapp.proto.AccountStatus" json:"status,omitempty"`
	Balance     int64         `protobuf:"varint,7,opt,name=balance" json:"balance,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Account) GetAcno() string {
	if m != nil {
		return m.Acno
	}
	return ""
}

func (m *Account) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Account) GetCino() string {
	if m != nil {
		return m.Cino
	}
	return ""
}

func (m *Account) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *Account) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

func (m *Account) GetStatus() AccountStatus {
	if m != nil {
		return m.Status
	}
	return AccountStatus_DISABLED
}

func (m *Account) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type CreateAccountRequest struct {
	// zas account id
	Acno string `protobuf:"bytes,1,opt,name=acno" json:"acno,omitempty"`
	// app user id
	Uid int64 `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	// customer unique number (phone)
	Cino string `protobuf:"bytes,3,opt,name=cino" json:"cino,omitempty"`
	// user remark
	Memo   string        `protobuf:"bytes,4,opt,name=memo" json:"memo,omitempty"`
	Status AccountStatus `protobuf:"varint,5,opt,name=status,enum=firstapp.proto.AccountStatus" json:"status,omitempty"`
}

func (m *CreateAccountRequest) Reset()                    { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()               {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateAccountRequest) GetAcno() string {
	if m != nil {
		return m.Acno
	}
	return ""
}

func (m *CreateAccountRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CreateAccountRequest) GetCino() string {
	if m != nil {
		return m.Cino
	}
	return ""
}

func (m *CreateAccountRequest) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *CreateAccountRequest) GetStatus() AccountStatus {
	if m != nil {
		return m.Status
	}
	return AccountStatus_DISABLED
}

type CreateAccountResponse struct {
	Status *Status  `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Data   *Account `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *CreateAccountResponse) Reset()                    { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()               {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateAccountResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CreateAccountResponse) GetData() *Account {
	if m != nil {
		return m.Data
	}
	return nil
}

type AccountQueryRequest struct {
	Acno string `protobuf:"bytes,1,opt,name=acno" json:"acno,omitempty"`
}

func (m *AccountQueryRequest) Reset()                    { *m = AccountQueryRequest{} }
func (m *AccountQueryRequest) String() string            { return proto.CompactTextString(m) }
func (*AccountQueryRequest) ProtoMessage()               {}
func (*AccountQueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AccountQueryRequest) GetAcno() string {
	if m != nil {
		return m.Acno
	}
	return ""
}

type AccountResponse struct {
	Status *Status  `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Data   *Account `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *AccountResponse) Reset()                    { *m = AccountResponse{} }
func (m *AccountResponse) String() string            { return proto.CompactTextString(m) }
func (*AccountResponse) ProtoMessage()               {}
func (*AccountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AccountResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *AccountResponse) GetData() *Account {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "firstapp.proto.Account")
	proto.RegisterType((*CreateAccountRequest)(nil), "firstapp.proto.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "firstapp.proto.CreateAccountResponse")
	proto.RegisterType((*AccountQueryRequest)(nil), "firstapp.proto.AccountQueryRequest")
	proto.RegisterType((*AccountResponse)(nil), "firstapp.proto.AccountResponse")
	proto.RegisterEnum("firstapp.proto.AccountStatus", AccountStatus_name, AccountStatus_value)
	proto.RegisterEnum("firstapp.proto.AccountType", AccountType_name, AccountType_value)
}

func init() { proto.RegisterFile("account.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x90, 0xd1, 0x4a, 0xeb, 0x40,
	0x14, 0x45, 0x3b, 0x6d, 0xda, 0xf4, 0x9e, 0xb4, 0xbd, 0x61, 0xee, 0x55, 0x07, 0x41, 0xa8, 0x79,
	0xaa, 0x15, 0x22, 0x54, 0xfc, 0x80, 0xb4, 0x0d, 0x28, 0x6a, 0xd1, 0xb4, 0x3e, 0xcb, 0x74, 0x3a,
	0x42, 0xc0, 0xcc, 0xc4, 0x64, 0xf2, 0xd0, 0x6f, 0xf1, 0x93, 0xfc, 0x29, 0x99, 0x49, 0x54, 0x5a,
	0x50, 0x10, 0xc4, 0xb7, 0xbd, 0x77, 0xf6, 0x9c, 0xb3, 0x72, 0xa0, 0x4b, 0x19, 0x93, 0x85, 0x50,
	0x7e, 0x9a, 0x49, 0x25, 0x71, 0xef, 0x21, 0xce, 0x72, 0x45, 0xd3, 0xb4, 0xf4, 0xfb, 0x1d, 0x26,
	0x93, 0x44, 0x8a, 0xd2, 0x79, 0x2f, 0x08, 0xec, 0xa0, 0xec, 0x63, 0x0c, 0x16, 0x65, 0x42, 0x12,
	0xd4, 0x47, 0x83, 0x3f, 0x91, 0xd1, 0xd8, 0x85, 0x46, 0x11, 0xaf, 0x48, 0xbd, 0x8f, 0x06, 0x8d,
	0x48, 0x4b, 0xdd, 0x62, 0xb1, 0x90, 0xa4, 0x51, 0xb6, 0xb4, 0xd6, 0x59, 0xc2, 0x13, 0x49, 0xac,
	0x32, 0xd3, 0x1a, 0x1f, 0x42, 0x87, 0x65, 0x9c, 0x2a, 0xbe, 0xba, 0x57, 0x71, 0xc2, 0x49, 0xd3,
	0x7c, 0x73, 0xaa, 0x6c, 0x11, 0x27, 0x1c, 0x9f, 0x41, 0x2b, 0x57, 0x54, 0x15, 0x39, 0x69, 0xf5,
	0xd1, 0xa0, 0x37, 0x3a, 0xf0, 0x37, 0x59, 0xfd, 0x8a, 0x6c, 0x6e, 0x4a, 0x51, 0x55, 0xc6, 0x04,
	0xec, 0x25, 0x7d, 0xa4, 0x82, 0x71, 0x62, 0x1b, 0xae, 0x37, 0xeb, 0x3d, 0x23, 0xf8, 0x3f, 0x31,
	0x0b, 0xaa, 0x97, 0x11, 0x7f, 0x2a, 0x78, 0xfe, 0xd3, 0xbf, 0xf6, 0xc1, 0xdd, 0xfc, 0x06, 0xb7,
	0xa7, 0x60, 0x67, 0x0b, 0x2e, 0x4f, 0xa5, 0xc8, 0x39, 0xf6, 0xdf, 0xe7, 0x69, 0x3e, 0x67, 0xb4,
	0xbb, 0x3d, 0x6f, 0xeb, 0x00, 0xc7, 0x60, 0xad, 0xa8, 0xa2, 0x06, 0xdd, 0x19, 0xed, 0x7d, 0xb2,
	0x3d, 0x32, 0x25, 0xef, 0x08, 0xfe, 0x55, 0xc1, 0x6d, 0xc1, 0xb3, 0xf5, 0x17, 0x17, 0xf1, 0x04,
	0xfc, 0xfd, 0x4d, 0xb4, 0xe1, 0x10, 0xba, 0x1b, 0x97, 0xc2, 0x1d, 0x68, 0x4f, 0x2f, 0xe6, 0xc1,
	0xf8, 0x2a, 0x9c, 0xba, 0x35, 0xec, 0x80, 0x1d, 0xce, 0x4a, 0x83, 0x86, 0x27, 0xe0, 0x54, 0xdd,
	0xc5, 0x3a, 0xe5, 0xb8, 0x0d, 0xd6, 0xdd, 0x3c, 0x8c, 0xdc, 0x9a, 0x56, 0xe3, 0x60, 0x76, 0xe9,
	0x22, 0xfd, 0xfa, 0x3a, 0x8c, 0x26, 0xe7, 0xc1, 0x6c, 0xe1, 0xd6, 0xc7, 0xf5, 0x1b, 0xb4, 0x6c,
	0x99, 0xad, 0xa7, 0xaf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x32, 0xb4, 0xe2, 0x02, 0x13, 0x03, 0x00,
	0x00,
}
