// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package firstapp_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Status struct {
	// code = 0 => success
	Code  int64  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Status) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Ping struct {
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *Ping) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Pong struct {
	Timestamp     int64  `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	SystemName    string `protobuf:"bytes,2,opt,name=system_name,json=systemName" json:"system_name,omitempty"`
	SystemVersion string `protobuf:"bytes,3,opt,name=system_version,json=systemVersion" json:"system_version,omitempty"`
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *Pong) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Pong) GetSystemName() string {
	if m != nil {
		return m.SystemName
	}
	return ""
}

func (m *Pong) GetSystemVersion() string {
	if m != nil {
		return m.SystemVersion
	}
	return ""
}

func init() {
	proto.RegisterType((*Status)(nil), "firstapp.proto.Status")
	proto.RegisterType((*Ping)(nil), "firstapp.proto.Ping")
	proto.RegisterType((*Pong)(nil), "firstapp.proto.Pong")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0xc1, 0x8a, 0xc2, 0x30,
	0x10, 0x40, 0x49, 0xdb, 0x2d, 0x74, 0x76, 0xb7, 0x87, 0xe0, 0xa1, 0x07, 0xc1, 0x52, 0x14, 0x7a,
	0xf2, 0xa0, 0x7f, 0xe0, 0x07, 0x48, 0xa9, 0xe0, 0x55, 0x62, 0x8d, 0x12, 0x70, 0x32, 0x21, 0x19,
	0x05, 0xff, 0x5e, 0x68, 0x0a, 0x1e, 0xbd, 0xcd, 0x7b, 0xbc, 0x61, 0x18, 0xf8, 0x1b, 0x08, 0x91,
	0xec, 0xda, 0x79, 0x62, 0x92, 0xe5, 0xd5, 0xf8, 0xc0, 0xca, 0xb9, 0xc8, 0xcd, 0x06, 0xf2, 0x03,
	0x2b, 0x7e, 0x04, 0x29, 0x21, 0x1b, 0xe8, 0xa2, 0x2b, 0x51, 0x8b, 0x36, 0xed, 0xc7, 0x59, 0xce,
	0xe0, 0x47, 0x7b, 0x4f, 0xbe, 0x4a, 0x6a, 0xd1, 0x16, 0x7d, 0x84, 0x66, 0x09, 0x59, 0x67, 0xec,
	0x4d, 0xce, 0xa1, 0x60, 0x83, 0x3a, 0xb0, 0x42, 0x37, 0xad, 0x7d, 0x44, 0x73, 0x87, 0xac, 0xa3,
	0x6f, 0x95, 0x5c, 0xc0, 0x6f, 0x78, 0x05, 0xd6, 0x78, 0xb2, 0x0a, 0xf5, 0x74, 0x07, 0xa2, 0xda,
	0x2b, 0xd4, 0x72, 0x05, 0xe5, 0x14, 0x3c, 0xb5, 0x0f, 0x86, 0x6c, 0x95, 0x8e, 0xcd, 0x7f, 0xb4,
	0xc7, 0x28, 0x77, 0x49, 0x27, 0xce, 0xf9, 0xf8, 0xd2, 0xf6, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xd8,
	0x5b, 0x88, 0xfb, 0xf2, 0x00, 0x00, 0x00,
}
